development:
  adapter: mysql2
  encoding: utf8
  database: blog_development
  username: root
  password: admin
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  database: blog_test
  username: root
  password: admin
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  database: blog_production
  username: root
  password: admin
  host: 127.0.0.1